### ISSUE TITLE
Make nodes bigger based on connectivity?

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/connectivity-search-frontend#46]
@ajlee21 had the idea that nodes could be bigger or smaller based on their connectivity. @dhimmel  Would we want to do something like this?

**Comment by dhimmel** [comment]
I have scaled node size by degree in the past ([like here](https://blog.dhimmel.com/friendship-network/)). I don't think it makes sense for the application here. Would you use the degree of just plotted edges or also edges that are not shown?

Once we compute scores for nodes (rather than just paths as we currently have), it may make sense to scale by node score. Let's keep this in mind.
